### ISSUE TITLE
add new languages to our site

### ISSUE THREAD

**Issue by Huseyin-Cinar** [The-Future-Software-Company/.github#6]
**@lytwest** if you can help me on adding new speaking languages for the Future I will so happy.

**Comment by Lytwest** [comment]
contact me in the afternoon @Huseyin-Cinar

**Comment by Huseyin-Cinar** [comment]
> contact me in the afternoon @Huseyin-Cinar

**@lytwest,** I want to transform the index page's content from turkish to franch. Can you help me?

**Comment by Huseyin-Cinar** [comment]
> > contact me in the afternoon @Huseyin-Cinar
> 
> **@Lytwest,** I want to transform the index page's content from turkish to franch. Can you help me?

You can see Index page's content in here `view-source:https://futuree.netlify.app`

**Comment by Lytwest** [comment]
@Huseyin-Cinar , It's too long, isn't it? About 800 lines.

**Comment by Huseyin-Cinar** [comment]
Yes, but we are translate the only elements who display's block. Like these `<h1>`, `<p>`, `<span>`, `<div>`

**Comment by Lytwest** [comment]
OK, I'm starting to do it now, I don't know exactly what we will do, but I would like to help, I estimate it will be finished around `17.30-18.00`.

**Comment by Huseyin-Cinar** [comment]
🥰 thank you!

**Comment by Lytwest** [comment]
I do not translate the places in the file where it says "The Future", I will leave it as it is. For example, instead of "The Future - Home Page", I define it as "The Future - Page d'accueil". For your information.

**Comment by Huseyin-Cinar** [comment]
Exactly!

**Comment by Huseyin-Cinar** [comment]
When you finished the translation, you should upload the document with `fr.html` name to a private repository in @thefuture-org. Then create an issue and mention me.

**Comment by Lytwest** [comment]
![image](https://user-images.githubusercontent.com/76743461/222906902-58191357-ac5b-4549-b810-f9f60245bc81.png)
Will they be edited here? More precisely, after the ID section?

**Comment by Huseyin-Cinar** [comment]
**No,** you should not edit the `id`, `class` sections. Only edit the sections who you can see on the page.

**Comment by Huseyin-Cinar** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/84516708/222907227-0498325d-986d-43b6-8c04-c6f0ba654d40.PNG)

like in here

**Comment by Lytwest** [comment]
Check the address https://github.com/thefuture-org/fr-lang/issues/

**Comment by Huseyin-Cinar** [comment]
**@Lytwest,**  the final edits to the page have been completed. It's now in perfect condition. I added your link to the `footer` of the page, If you want i can change it.

https://futuree.netlify.app/fr
https://futuree.netlify.app/fr/entree
https://futuree.netlify.app/fr/profil
https://futuree.netlify.app/fr/codage
https://futuree.netlify.app/fr/applications
